In [52]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import sem
import requests
import json
from pprint import pprint

In [53]:
cities_df = pd.read_csv("worldcities.csv")
sample_df = cities_df.sample(500)
worldcities = sample_df.round(2)
worldcities.reset_index(inplace = True)
del worldcities['index']
worldcities.head()

  Country        City  Latitude  Longitude
0      cn     qiqihar     47.34     123.97
1      in      pirawa     24.17      76.03
2      br    campanha    -21.83     -45.40
3      hu  asotthalom     46.20      19.78
4      ru   kedrovoye     57.16      60.57

In [54]:
url = "http://api.openweathermap.org/data/2.5/weather?"
query_url = f"{url}&units=imperial&appid=86e99f8f52b689a868c3db258b66be67&q="

In [56]:
cities = worldcities['City']
humidity = []
cityid = []
maxt = []
cloud = []
wind = []
date = []
country = []
lat = []
lon = []

for city in cities:
    
    response = requests.get(query_url + city)
    response2 = response.json()
    lat.append(response2['coord']['lat'])
    lon.append(response2['coord']['lon'])
    humidity.append(response2['main']['humidity'])
    cityid.append(response2['id'])
    maxt.append(response2['main']['temp_max'])
    cloud.append(response2['clouds']['all'])
    wind.append(response2['wind']['speed'])
    date.append(response2['dt'])
    country.append(response2['sys']['country'])
    
print(f"Retrieving Results...")

#try:
    #print(f"The city of {cities} has the ID {cityid}.")
        
#except (KeyError, IndexError):
    #print("Missing field/result... skipping.")
        
    #print("------------")
    
#print(f"The latitude information received is: {lat}")
#print(f"The longitude information received is: {lon}")
#print(f"The humidity information received is: {humidity}")
#print(f"The ID information received is: {cityid}")
#print(f"The max temperature information received is: {maxt}")
#print(f"The cloudiness information received is: {cloud}")
#print(f"The wind information received is: {wind}")
#print(f"The date information received is: {date}")
#print(f"The country information received is: {country}")

KeyError: 'coord'

In [44]:
weather_dict = {
    "City": cities,
    "Latitude": lat,
    "Longitude": lon,
    "Max temperature(F)": maxt,
    "Humidity(%)": humidity,
    "Cloudiness": cloud,
    "Wind Speed": wind,
    "Country": country,
    "Date": date,
}
weather_data = pd.DataFrame(weather_dict)
weather_data.head()

,City,Latitude,Longitude,Max temperature(F),Humidity(%),Cloudiness,Wind Speed,Country,Date
0,obligado,-27.03,-55.63,86.00,48,60,3.36,PY,1601423890
1,kwakoa,-3.77,37.72,69.04,75,84,3.33,TZ,1601423890
2,zhemtala,43.28,43.66,50.00,81,40,2.24,RU,1601423890
3,milharado,38.95,-9.20,64.00,72,100,8.05,PT,1601423890
4,tubod,8.06,123.79,82.11,73,54,0.34,PH,1601423891